# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nodes.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bnodes.proto\x12\x04raft\"\x18\n\x05Nodes\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"\"\n\x0fServeClientArgs\x12\x0f\n\x07Request\x18\x01 \x01(\t\"C\n\x10ServeClientReply\x12\x0c\n\x04\x44\x61ta\x18\x01 \x01(\t\x12\x10\n\x08LeaderID\x18\x02 \x01(\t\x12\x0f\n\x07Success\x18\x03 \x01(\x08\"1\n\x0bVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\t\"M\n\tVoteReply\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\x12\x1c\n\x14leader_lease_timeout\x18\x03 \x01(\x05\"\xa6\x01\n\x0e\x45ntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x05\x12\x15\n\rprev_log_term\x18\x04 \x01(\x05\x12\x15\n\rleader_commit\x18\x05 \x01(\x05\x12\x1c\n\x14leader_lease_timeout\x18\x06 \x01(\x05\x12\x0f\n\x07\x65ntries\x18\x07 \x03(\t\"-\n\x0c\x45ntriesReply\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\xbc\x01\n\x13RaftManagerServicer\x12,\n\x06Voting\x12\x11.raft.VoteRequest\x1a\x0f.raft.VoteReply\x12\x39\n\rAppendEntries\x12\x14.raft.EntriesRequest\x1a\x12.raft.EntriesReply\x12<\n\x0bServeClient\x12\x15.raft.ServeClientArgs\x1a\x16.raft.ServeClientReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nodes_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NODES']._serialized_start=21
  _globals['_NODES']._serialized_end=45
  _globals['_SERVECLIENTARGS']._serialized_start=47
  _globals['_SERVECLIENTARGS']._serialized_end=81
  _globals['_SERVECLIENTREPLY']._serialized_start=83
  _globals['_SERVECLIENTREPLY']._serialized_end=150
  _globals['_VOTEREQUEST']._serialized_start=152
  _globals['_VOTEREQUEST']._serialized_end=201
  _globals['_VOTEREPLY']._serialized_start=203
  _globals['_VOTEREPLY']._serialized_end=280
  _globals['_ENTRIESREQUEST']._serialized_start=283
  _globals['_ENTRIESREQUEST']._serialized_end=449
  _globals['_ENTRIESREPLY']._serialized_start=451
  _globals['_ENTRIESREPLY']._serialized_end=496
  _globals['_RAFTMANAGERSERVICER']._serialized_start=499
  _globals['_RAFTMANAGERSERVICER']._serialized_end=687
# @@protoc_insertion_point(module_scope)
