# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import nodes_pb2 as nodes__pb2


class RaftManagerServicerStub(object):
    """RaftManagerServicer is the service definition for Raft.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Voting = channel.unary_unary(
                '/raft.RaftManagerServicer/Voting',
                request_serializer=nodes__pb2.VoteRequest.SerializeToString,
                response_deserializer=nodes__pb2.VoteReply.FromString,
                )
        self.AppendEntries = channel.unary_unary(
                '/raft.RaftManagerServicer/AppendEntries',
                request_serializer=nodes__pb2.EntriesRequest.SerializeToString,
                response_deserializer=nodes__pb2.EntriesReply.FromString,
                )
        self.ServeClient = channel.unary_unary(
                '/raft.RaftManagerServicer/ServeClient',
                request_serializer=nodes__pb2.ServeClientArgs.SerializeToString,
                response_deserializer=nodes__pb2.ServeClientReply.FromString,
                )


class RaftManagerServicerServicer(object):
    """RaftManagerServicer is the service definition for Raft.
    """

    def Voting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServeClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RaftManagerServicerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Voting': grpc.unary_unary_rpc_method_handler(
                    servicer.Voting,
                    request_deserializer=nodes__pb2.VoteRequest.FromString,
                    response_serializer=nodes__pb2.VoteReply.SerializeToString,
            ),
            'AppendEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEntries,
                    request_deserializer=nodes__pb2.EntriesRequest.FromString,
                    response_serializer=nodes__pb2.EntriesReply.SerializeToString,
            ),
            'ServeClient': grpc.unary_unary_rpc_method_handler(
                    servicer.ServeClient,
                    request_deserializer=nodes__pb2.ServeClientArgs.FromString,
                    response_serializer=nodes__pb2.ServeClientReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'raft.RaftManagerServicer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RaftManagerServicer(object):
    """RaftManagerServicer is the service definition for Raft.
    """

    @staticmethod
    def Voting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/raft.RaftManagerServicer/Voting',
            nodes__pb2.VoteRequest.SerializeToString,
            nodes__pb2.VoteReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AppendEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/raft.RaftManagerServicer/AppendEntries',
            nodes__pb2.EntriesRequest.SerializeToString,
            nodes__pb2.EntriesReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ServeClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/raft.RaftManagerServicer/ServeClient',
            nodes__pb2.ServeClientArgs.SerializeToString,
            nodes__pb2.ServeClientReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
